runtime! debian.vim

if has("syntax")
  syntax on
endif

runtime! debian.vim

if has("syntax")
  syntax on
endif

set hlsearch
set nu
set autoindent
set ts=4
set sts=4
set cindent
set laststatus=2
set shiftwidth=4
set showmatch
set smartcase
set smarttab
set smartindent
set ruler
set fileencodings=utf8,euc-kr

if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif
